spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  devtools:
    livereload:
      enabled: true
  management:
    server:
      port: 8080
    endpoint:
      health:
        show-details: always
    endpoints:
      web:
        exposure:
          include: "*"
      enabled-by-default: true
  logging:
    level:
      com.example: DEBUG
